(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(* Gaunt coeff for Real Ylm's: only for {l,lp,lpp} = {2,2,2} *)
GauntReal[l_,n_,np_,npp_]:=Module[{GC,A,B,coefCYlm,valGC},

(* Gaunt coeff for Complex Ylm's; {l,lp,lpp} = {2,2,2} *)GC[m_,mp_,mpp_]:=If[m+mp+mpp==0, Sqrt[(5)(5)(2l+1)/(4Pi)]ThreeJSymbol[{2,0},{2,0},{l,0}]ThreeJSymbol[{2,m},{2,mp},{l,mpp}],0];

A[m_]:=If[m<0,I/Sqrt[2],If[m==0,1,(-1)^m/Sqrt[2]]];
B[m_]:=If[m<0,-I(-1)^m/Sqrt[2],If[m==0,0,1/Sqrt[2]]];

(* Real Ylm can be written as superpositions of complex Ylm's with \[PlusMinus]m; 
 A[m] is coeff of Y_l^{m}; B[m] is coeff of Y_l^{-m};*)
coefCYlm[m_,mp_,mpp_]:={A[m]A[mp]A[mpp],A[m]A[mp]B[mpp],A[m]B[mp]A[mpp],A[m]B[mp]B[mpp],B[m]A[mp]A[mpp],B[m]A[mp]B[mpp],
B[m]B[mp]A[mpp],B[m]B[mp]B[mpp]};
(* +ve m for A, -ve m for B terms *)
valGC[m_,mp_,mpp_]:={GC[m,mp,mpp],GC[m,mp,-mpp],GC[m,-mp,mpp],GC[m,-mp,-mpp],GC[-m,mp,mpp],GC[-m,mp,-mpp],GC[-m,-mp,mpp],GC[-m,-mp,-mpp]};

coefCYlm[n,np,npp].valGC[n,np,npp]
];

(* Gaunt coeff for Real Ylm's: only for {l,lp,lpp} = {2,2,0} *)
GR0[n_,np_,npp_]:=GauntReal[0,n,np,npp];
(* Gaunt coeff for Real Ylm's: only for {l,lp,lpp} = {2,2,2} *)
GR2[n_,np_,npp_]:=GauntReal[2,n,np,npp];
(* Gaunt coeff for Real Ylm's: only for {l,lp,lpp} = {2,2,4} *)
GR4[n_,np_,npp_]:=GauntReal[4,n,np,npp];
