(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
vsA :={{{Vlm[2,-2]->(64 Sqrt[(3 \[Pi])/5] Cos[\[Beta]]^2 (Cos[\[Alpha]]^3 (2+Cos[2 \[Beta]])^(5/2)-(3+Cos[2 \[Alpha]]+2 Cos[2 \[Beta]])^(5/2)/(4 Sqrt[2])) Sec[\[Alpha]]^3)/((Cos[\[Alpha]]^2+2 Cos[\[Beta]]^2) (2+Cos[2 \[Beta]]))^(5/2),Vlm[2,-1]->0,Vlm[2,0]->(8 Sqrt[\[Pi]/5] Sec[\[Alpha]]^3 (-4 Cos[\[Alpha]]^3 (2+Cos[2 \[Beta]])^(5/2) (-Cos[2 \[Alpha]]+Cos[2 \[Beta]])+Sqrt[2] (3+Cos[2 \[Alpha]]+2 Cos[2 \[Beta]])^(5/2) Sin[\[Beta]]^2))/((Cos[\[Alpha]]^2+2 Cos[\[Beta]]^2) (2+Cos[2 \[Beta]]))^(5/2),Vlm[2,1]->0,Vlm[2,2]->0}},{{Vlm[4,-4]->0,Vlm[4,-3]->0,Vlm[4,-2]->(64 Sqrt[5 \[Pi]] Cos[\[Beta]]^2 (-2 Cos[\[Alpha]]^5 (2+Cos[2 \[Beta]])^(9/2) (-2-3 Cos[2 \[Alpha]]+Cos[2 \[Beta]])+((-5+Cos[2 \[Beta]]) (3+Cos[2 \[Alpha]]+2 Cos[2 \[Beta]])^(9/2))/(8 Sqrt[2])) Sec[\[Alpha]]^5)/(3 ((Cos[\[Alpha]]^2+2 Cos[\[Beta]]^2) (2+Cos[2 \[Beta]]))^(9/2)),Vlm[4,-1]->0,Vlm[4,0]->(Sqrt[\[Pi]] (-32 Cos[\[Alpha]]^5 (2+Cos[2 \[Beta]])^(9/2) (9-2 Cos[4 \[Alpha]]+12 Cos[2 \[Beta]]+8 Cos[2 \[Alpha]] (2+3 Cos[2 \[Beta]])-3 Cos[4 \[Beta]])+Sqrt[2] (3+Cos[2 \[Alpha]]+2 Cos[2 \[Beta]])^(9/2) (-23-36 Cos[2 \[Beta]]+3 Cos[4 \[Beta]])) Sec[\[Alpha]]^5)/(6 ((Cos[\[Alpha]]^2+2 Cos[\[Beta]]^2) (2+Cos[2 \[Beta]]))^(9/2)),Vlm[4,1]->0,Vlm[4,2]->0,Vlm[4,3]->0,Vlm[4,4]->-((128 Sqrt[35 \[Pi]] Cos[\[Beta]]^4 (Cos[\[Alpha]]^5 (2+Cos[2 \[Beta]])^(9/2)+(3+Cos[2 \[Alpha]]+2 Cos[2 \[Beta]])^(9/2)/(16 Sqrt[2])) Sec[\[Alpha]]^5)/(3 ((Cos[\[Alpha]]^2+2 Cos[\[Beta]]^2) (2+Cos[2 \[Beta]]))^(9/2)))}}};


(* ::Input::Initialization:: *)
vsB:={{{Vlm[2,-2]->(64 Sqrt[(3 \[Pi])/5] Abs[Cos[\[Beta]]] Sec[\[Beta]]^4 Sin[\[Alpha]]^2)/(3+Cos[2 \[Alpha]])^(5/2),Vlm[2,-1]->0,Vlm[2,0]->4 Sqrt[\[Pi]/5] (Abs[Cos[\[Alpha]]] Sec[\[Alpha]]^4-(8 Abs[Cos[\[Beta]]] Sec[\[Beta]]^4)/(3+Cos[2 \[Alpha]])^(3/2)),Vlm[2,1]->0,Vlm[2,2]->0}},{{Vlm[4,-4]->0,Vlm[4,-3]->0,Vlm[4,-2]->-((128 Sqrt[5 \[Pi]] Abs[Cos[\[Beta]]] Sec[\[Beta]]^6 Sin[\[Alpha]]^2)/(3 (3+Cos[2 \[Alpha]])^(7/2))),Vlm[4,-1]->0,Vlm[4,0]->4/3 Sqrt[\[Pi]] (Abs[Cos[\[Alpha]]] Sec[\[Alpha]]^6+(24 Abs[Cos[\[Beta]]] Sec[\[Beta]]^6)/(3+Cos[2 \[Alpha]])^(5/2)),Vlm[4,1]->0,Vlm[4,2]->0,Vlm[4,3]->0,Vlm[4,4]->-((16 Sqrt[35 \[Pi]] Abs[Cos[\[Beta]]] (-13-20 Cos[2 \[Alpha]]+Cos[4 \[Alpha]]) Sec[\[Beta]]^6)/(3 (3+Cos[2 \[Alpha]])^(9/2)))}}};


(* ::Input::Initialization:: *)
VlmsRulesA:=vsA//Flatten ;
VlmsRulesB:=vsB//Flatten ;
